In [31]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [32]:
names = ["sepal-length", "sepal-width", "petal-length", "petal-width","class"]
dataset = pd.read_csv("iris.data", names=names)
dataset

sepal-length  sepal-width  petal-length  petal-width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [33]:
X = dataset.drop(columns = "class", axis = 1)
Y = dataset["class"]

In [34]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=0)

In [35]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [36]:
pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [37]:
explained_varience = pca.explained_variance_ratio_

In [38]:
def perform_pca(n):
    X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=0)
    pca = PCA(n_components=n)
    pca_x_train = pca.fit_transform(X_train)
    pca_x_test = pca.transform(X_test)
    classifier = RandomForestClassifier(max_depth=2, random_state=0)
    classifier.fit(pca_x_train, Y_train)
    Y_pred = classifier.predict(pca_x_test)
    cm = confusion_matrix(Y_test, Y_pred)
    print(cm)
    print("Accuracy {0}\n\n".format(accuracy_score(Y_test,Y_pred)))

In [39]:
for x in range(1,5): perform_pca(x)

[[11  0  0]
 [ 0 12  1]
 [ 0  2  4]]
Accuracy 0.9


[[11  0  0]
 [ 0  8  5]
 [ 0  1  5]]
Accuracy 0.8


[[11  0  0]
 [ 0  5  8]
 [ 0  1  5]]
Accuracy 0.7


[[11  0  0]
 [ 0 11  2]
 [ 0  1  5]]
Accuracy 0.9


