## Unsupervised - LDA(latent-dirichlet-allocation)

In [12]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [13]:
names = ["sepal-length", "sepal-width", "petal-length", "petal-width","class"]
dataset = pd.read_csv("iris.data", names=names)
dataset

sepal-length  sepal-width  petal-length  petal-width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [14]:
X = dataset.iloc[:, 0:4]
Y = dataset.iloc[:, 4]

In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=0)

In [16]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, Y_train)
Y_pred = classifier.predict(X_test)

In [18]:
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
print("Accuracy :- " + str(accuracy_score(Y_test, Y_pred)))

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
Accuracy :- 1.0


#### Using LDA and dropping 1 column below is the analysis

In [20]:
lda = LDA(n_components=1) # drop 1 column
lda_X_train = lda.fit_transform(X_train, Y_train) # here we use X_train and Y_train both
lda_X_test = lda.transform(X_test)

In [21]:
classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(lda_X_train, Y_train)
Y_pred = classifier.predict(lda_X_test)

In [22]:
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
print("Accuracy :- " + str(accuracy_score(Y_test, Y_pred)))

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
Accuracy :- 1.0
